image: python:3.7.4-alpine3.10

pipelines:
  tags:
    ecr-release-*:
      - step:
          services:
            - docker
          caches:
            - pip
          script:
            - pip3 install awscli
            - ECR_REPOSITORY="kokos-node-gibus"
            - IMAGE_TAG="latest"
            - aws configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}"
            - aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}"
            - login_ecr=$(eval $(aws ecr get-login --no-include-email --region eu-south-1 | sed 's;https://;;g'))
            - echo "$login_ecr"
            - ECR_REGISTRY=${{ login-ecr.outputs.registry }}
            - docker build -t  $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            - docker push  $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG