export { calcParObjTense }

import { calcTenseInput } from "./class4tense";

function calcParObjTense(data: any) {
    let parObjTense: any = calcTenseInput();
    //SPORGENZA, LARGHEZZA, CLIENTE, ORDINE, GAMBE, TIPO_GAMBA, POSIZIONE_GAMBA_TELESCOPICA, TIPO_SUPP_CASSONETTO, ZIP, TIPO_ATT_SOFFITTO, ACCOPPIAMENTO, TIPO_ACCOPPIAMENTO, MOTORE, LATO_MOTORE, LED_CASSONETTO, LED_FRANGITRATTA, LED_GUIDE, ALTEZZA_GAMBA_SX, ALTEZZA_GAMBA_DX, VERSIONE_SUPPORTO, TIPOLOGIA_SUPPORTO, SUPPORTI_AGGIUNTIVI_GUIDA, ALTEZZA_SUPPORTO_GUIDA, VOLANT, ALTEZZA_VOLANT, FRANGITRATTA, TETTUCCIO)

    return parObjTense;
}